name: Test upgrade in a kind cluster
on:
  push:
    branches: [ "main" ]
  pull_request:
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go 1.21.1
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.1"
      - name: ⛴️ Run test in kind cluster ⛴️
        run: |
          FORCE_COLOR=true make test-in-kind
